### ISSUE TITLE
Make faillure with Armbian linux

### ISSUE THREAD

**Issue by khoahung** [McMCCRU/rtl8188gu#74]
I used this kernel Linux armbian 6.12.17-ophub
build with toolchain Arm GNU Toolchain 14.2.Rel1 (Build arm-14.52)) 14.2.1 20241119

make by this command line:

 make ARCH=arm64 CROSS_COMPILE=/home/khoahung/arm-toolchain/arm-gnu-toolchain-14.2.rel1/bin/aarch64-none-elf- -C /lib/modules/6.12.17-ophub/build M=/home/khoahung/rtl8188gu  modules

error

/home/khoahung/rtl8188gu/os_dep/linux/usb_intf.c:320:17: error: 'struct usb_driver' has no member named 'drvwrap'
  320 |         .usbdrv.drvwrap.driver.shutdown = rtw_dev_shutdown,
      |                 ^~~~~~~
/home/khoahung/rtl8188gu/os_dep/linux/usb_intf.c:320:43: error: initialization of 'const char *' from incompatible pointer type 'void (*)(struct device *)' [-Wincompatible-pointer-types]
  320 |         .usbdrv.drvwrap.driver.shutdown = rtw_dev_shutdown,
      |                                           ^~~~~~~~~~~~~~~~
/home/khoahung/rtl8188gu/os_dep/linux/usb_intf.c:320:43: note: (near initialization for 'usb_drv.usbdrv.name')
/home/khoahung/rtl8188gu/os_dep/linux/usb_intf.c:981:5: warning: no previous prototype for 'rtw_resume_process' [-Wmissing-prototypes]
  981 | int rtw_resume_process(_adapter *padapter)
      |     ^~~~~~~~~~~~~~~~~~
/home/khoahung/rtl8188gu/os_dep/linux/usb_intf.c:1235:11: warning: no previous prototype for 'rtw_usb_primary_adapter_init' [-Wmissing-prototypes]
 1235 | _adapter *rtw_usb_primary_adapter_init(struct dvobj_priv *dvobj,
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:229: /home/khoahung/rtl8188gu/os_dep/linux/usb_intf.o] Error 1
make[2]: *** [/usr/src/linux-headers-6.12.17-ophub/Makefile:1932: /home/khoahung/rtl8188gu] Error 2
make[1]: *** [Makefile:224: __sub-make] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.12.17-ophub'
make: *** [Makefile:1895: modules] Error 2
